// you can add any STATIC data you want here
import pkg from "../package.json"

import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
 english:{
   about_advanced_eye_center_1: "Advanced Eye Center was opened in 2012 with the goal to offer the people of South Florida, the United States, and the world over, the most innovative treatments to improve your vison.",
   about_advanced_eye_center_2: "We are proud to say we have treated patients using a variety of treatments, including laser techniques, from numerous countries spanning the globe, such as: The United States, Canada, Mexico, Nicaragua, El Salvador, Honduras, Panama, Cuba, Jamaica, The Dominican Republic, Trinidad and Tobago, Aruba, Haiti, Colombia, Venezuela, Brazil, Ecuador, Peru, Bolivia, Chile, Argentina, Uruguay, Spain, France, the United Kingdom, Germany, Switzerland, Italy, Poland, The Ukraine, Japan, Australia, the United Arab Emirates, and South Africa. Our dream was to provide as much healthcare to as many people on Earth, and that dream is now a reality.",
   about_belalcazar_1: "A native of Colombia, Dr. Belalcazar received his MD there and completed his residency at the Colombian Institute of Ocular Surgery, affiliated to the Pontifical Xavierian University in Bogotá. He underwent Refractive Surgery training at the world famous Barraquer Institute of America in 1993, The Myopia Ocular Center in Madrid in 1996, and completed a Refractive Laser Surgery Fellowship at Park Avenue Laser Vision in New York with Emil W. Chynn, MD, world renowned Refractive Surgeon, in 2008.",
   about_belalcazar_2: "Dr. Belalcazar has performed thousands of Radial Keratotomy (RK) surgeries, Cataracts and Corneal Transplants at the Surgical Ocular Institute Palermo and was the Director of the Eye Clinic at the University Foundation of San Martin in Colombia. He has performed over 5,000 LASIK, LASEK and EPI-LASEK procedures, and more than 3000 Glaucoma and other Ophthalmology Laser surgeries. Dr. Belalcazar performs Phaco Cataract surgery at the Beraja Medical Institute in Coral Gables, the Larkin Hospital in Miami, the North Miami Surgical Center and the Palm Springs Hospital. He has been the recipient of numerous awards and recognitions, including the Colombian Culture & Heritage Award for his professional achievement and service to the national community, and multiple recognitions for Outstanding and Professional Excellence from the State Senate, Council and Assembly of New York.",
   about_belalcazar_3: "Dr. Belalcazar is a naturalized US citizen, has completed a Pediatrics residency at Driscol Children’s Hospital, Texas A. & M., is certified by the Educational Council for Foreign Medical Graduates of Medical Examiners, and is licensed by the Florida, Georgia, New York, and Texas State Medical Boards. He is a Member of The American Academy of Ophthalmology, American Society of Cataract and Refractive Surgery and The International Society of Refractive Surgery. He became the Medical Director of Vision Specialty Care for South Florida in 2010, and in 2012 Dr. Belalcazar opened Advanced Eye Center to serve his patients in South Florida with the most innovated and latest equipment. He is part of several leading researchers in Glaucoma, Diabetic Retinopathy, Refractive surgery and Keratoconus in the country. Dr. Belalcazar’s Advanced Eye Center is one of the first centers in South Florida to offer Collagen Crosslinking for Keratoconus, Corneal Warpage and Ectasia. He enjoys Mountain and Rock Climbing, Marathons, Triathlons, Scuba diving, and Skydiving."
 },
 español: {
   about_advanced_eye_center_1: "Advanced Eye Center fue inagurado en el 2012 con el objetivo de ofrecer a la poblacion del Sur de La Florida, los Estados Unidos y el mundo entero los tratamientos mas innovativos para mejorar su vision.",
   about_advanced_eye_center_2: "Estamos orgullosos hoy de recivir pacientes de todo el mundo con una variedad de tratamientos, incluyendo tecnicas de Laser. Hemos atendido pacientes de paises como: Los Estados Unidos, Canada, Mexico, Nicaragua, El Salvador, Honduras, Panama, Cuba, Jamaica, La Republica Dominicana, Trinidad y Tobago, Aruba, Haiti, Colombia, Venezuela, Brasil, Ecuador, Peru, Bolivia, Chile, Argentina, Uruguay, Espana, Francia, Inglaterra, Alemania, Suiza, Italia, Polonia, Ucrania, Japon, Australia, Los Emiratos Arabes y Sur Africa. El sueno de ofrecer una mejor salud a la mayor poblacion posible de la Tierra es ahora una realidad.",
   about_belalcazar_1: "El Dr Belalcazar, originario de Colombia, recivio alli su titulo de Doctor en Medicina y Cirugia y completo su especializacion en el Instituto Colombiano de Cirugia Ocular afiliado a la Pontificia Universidad Javeriana en Bogota. Realizo ademas entrenamientos en Cirugia Refractiva en el mundialmente reconocido Instituto Barraquer de America en 1993, en el Centro Ocular de Miopia en Madrid, Espana en 1996 y completo tambien un Fellowship en Cirugia Refractiva con Laser en Park Avenue Laser Vision en el 2008 con el Dr. Emil W. Chynn, cirujano refractive reconocido internacionalmente.",
   about_belalcazar_2: "El Dr. Belalcazar realizo miles de cirugias de Queratotomia Radial, Catarata y Transplantes de Cornea en el Instituto Palermo de Cirugia Ocular y fue Director de la Clinica de Oftalmologia de la Fundacion Universitaria San Martin en Colombia. Ha realizado mas de 5000 cirugias de LASIK, LASEK y EPI-LASEK, y mas de 3000 cirugias laser oculares de otros tipos y de Glaucoma. El Dr. Belalcazar realiza cirugias de Phacoemulsificacion para catarata en el Instituto Medico Beraja de Coral Gables, El Hospital Larkin de Miami, El Centro Quirurgico de North Miami y el Hospital de Palm Springs. El ha recivido numerosos premios y reconocimientos, incluyendo la condecoracion de Herencia y Cultura Colombiana por sus exitos profesionales y su servicio la comunidad y multiples reconocimientos por su sobresaliente y excelente desempeno profesional por parte del Senado, Concejo y la Asamblea de New York.",
   about_belalcazar_3: "El Dr. Belalcazar es Ciudadano Naturalizado de los Estados Unidos, completo su especializacion en Pediatria en el Driscoll Children’s Hospital afiliado a la Universidad de Texas, es certificado por el Concejo de Examinadores Medicos de Graduados Extrangeros, es Licensiado por el Board de La Florida, Georgia, New York y Texas. Es miembro de la Academia Americana de Oftalmologia, la Sociedad Americana de Catarata y Cirugia Refractiva y la Sociedad Internacional de Cirugia Refractiva. En el 2010 fue elegido como el Director Medico de “Vision Specialty Care” para el sur de la Florida, y en el 2012 el Dr. Belalcazar inicio el “Advanced Eye Center” para atender sus pacientes del sur de la Florida con las tecnicas y los equipos mas avanzados posibles. Ahora el es parte de varios grupos que lideran la investigacion en Glaucoma, Retinopatia Diabetica, Cirugia Refractiva y Keratocono en el pais. El “Advanced Eye Center” del Dr. Belalcazar es uno de los primeros centros del Sur de La Florida en ofrecer cirugia de “Collagen Crossliking” para keratocono y deformacion corneal. El dedica su tiempo libre al Montanismo, la Escalada en Roca, los Marathones, Triatlones, Buceo y Caida libre en paracaidismo."
 }
});


export default {
  pkg,
  strings
  // you can add any DYNAMIC data you need here
  // ...
}
